CREATE TABLE `users` (
  `id`                   bigint(20)    NOT NULL,
  `instance_id`          int           NOT NULL DEFAULT 0,
  `aud`                  varchar(255)  NOT NULL DEFAULT '',
  `role`                 varchar(255)  NOT NULL DEFAULT '',
  `email`                varchar(255)  NOT NULL DEFAULT '',
  `encrypted_password`   varchar(255)  NOT NULL DEFAULT '',
  `confirmed_at`         datetime     NOT NULL DEFAULT '2000-01-01 00:00:00',
  `invited_at`           datetime     NOT NULL DEFAULT '2000-01-01 00:00:00',
  `confirmation_token`   varchar(255)  NOT NULL DEFAULT '',
  `confirmation_sent_at` datetime     NOT NULL DEFAULT '2000-01-01 00:00:00',
  `recovery_token`       varchar(255)  NOT NULL DEFAULT '',
  `recovery_sent_at`     datetime     NOT NULL DEFAULT '2000-01-01 00:00:00',
  `email_change_token`   varchar(255)  NOT NULL DEFAULT '',
  `email_change`         varchar(255)  NOT NULL DEFAULT '',
  `email_change_sent_at` datetime     NOT NULL DEFAULT '2000-01-01 00:00:00',
  `last_sign_in_at`      datetime     NOT NULL DEFAULT '2000-01-01 00:00:00',
  `raw_app_meta_data`    text NOT NULL DEFAULT '{}',
  `raw_user_meta_data`   text NOT NULL DEFAULT '{}',
  `is_super_admin`       tinyint(1)    NOT NULL DEFAULT 0,
  `created_at`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `users_instance_id_idx` (`instance_id`),
  KEY `users_instance_id_email_idx` (`instance_id`, `email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
