// Code generated by crud. DO NOT EDIT.

package auditlogentries

import (
	"time"

	"github.com/goflower-io/xsql"
	"github.com/goflower-io/xsql/dialect"
	"maps"
	"slices"
)

type AuditLogEntries struct {
	Id         int64     `json:"id"`          //
	InstanceId int64     `json:"instance_id"` //
	Payload    string    `json:"payload"`     //
	CreatedAt  time.Time `json:"created_at"`  //
}

const (
	// table tableName is audit_log_entries
	table = "audit_log_entries"
	//Id
	Id = "id"
	//InstanceId
	InstanceId = "instance_id"
	//Payload
	Payload = "payload"
	//CreatedAt
	CreatedAt = "created_at"
)

var columns = []string{
	Id,
	InstanceId,
	Payload,
	CreatedAt,
}

var columnsSet = map[string]struct{}{
	Id:         {},
	InstanceId: {},
	Payload:    {},
	CreatedAt:  {},
}

func Columns() []string {
	return slices.Clone(columns)
}
func ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}

func (a *AuditLogEntries) NewPtr() any {
	return &AuditLogEntries{}
}
func (a *AuditLogEntries) IsNil() bool {
	return a == nil
}

func (u *AuditLogEntries) ScanDst(aa any, columns []string) []any {
	if a, ok := aa.(*AuditLogEntries); ok {
		dst := make([]interface{}, 0, len(columns))
		for _, v := range columns {
			switch v {
			case Id:
				dst = append(dst, &a.Id)
			case InstanceId:
				dst = append(dst, &a.InstanceId)
			case Payload:
				dst = append(dst, &a.Payload)
			case CreatedAt:
				dst = append(dst, &a.CreatedAt)
			}
		}
		return dst
	}
	return []any{}

}

func (a *AuditLogEntries) Values() []any {
	if a.IsNil() {
		return []any{}
	}
	return []interface{}{a.Id, a.InstanceId, a.Payload, a.CreatedAt}
}
func (a *AuditLogEntries) GetAutoIncrPk() (int64, string) {

	if a.IsNil() {
		return 0, Id
	}
	return a.Id, Id

}
func (a *AuditLogEntries) SetAutoIncrPk(id int64) {

	if a.IsNil() {
		return
	}
	a.Id = int64(id)

}

func (a *AuditLogEntries) Columns() []string {
	return slices.Clone(columns)
}
func (a *AuditLogEntries) ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}
func (a *AuditLogEntries) Schema() string {
	return ""
}

func (a *AuditLogEntries) Dialect() string {

	return dialect.MySQL
}
func (a *AuditLogEntries) Table() string {
	return table
}

const (
	IdOp = xsql.FieldOp[int64](Id)

	InstanceIdOp = xsql.FieldOp[int64](InstanceId)

	PayloadOp = xsql.StrFieldOp(Payload)

	CreatedAtOp = xsql.FieldOp[string](CreatedAt)
)

func And(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.AndOp(predicates...)
}
func Or(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.OrOp(predicates...)
}
func Not(predicate xsql.WhereFunc) xsql.WhereFunc {
	return xsql.NotOp(predicate)
}

func Create(db xsql.ExecQuerier) *Creater {
	return &Creater{xsql.NewInsertExecutor[*AuditLogEntries](db)}
}

type Creater struct {
	*xsql.InsertExecutor[*AuditLogEntries]
}

func (c *Creater) SetAuditLogEntries(a ...*AuditLogEntries) *Creater {
	c.SetItems(a...)
	return c
}

func Find(db xsql.ExecQuerier) *xsql.SelectExecutor[*AuditLogEntries] {
	return xsql.NewSelectExecutor[*AuditLogEntries](db)
}
func Delete(db xsql.ExecQuerier) *xsql.DeleteExecutor[*AuditLogEntries] {
	return xsql.NewDeleteExecutor[*AuditLogEntries](db)
}
func Update(db xsql.ExecQuerier) *Updater {
	return &Updater{xsql.NewUpdateExecutor[*AuditLogEntries](db)}
}

type Updater struct {
	*xsql.UpdateExecutor[*AuditLogEntries]
}

func (u *Updater) SetId(arg int64) *Updater {
	u.Set(Id, arg)
	return u
}

func (u *Updater) SetInstanceId(arg int64) *Updater {
	u.Set(InstanceId, arg)
	return u
}

func (u *Updater) AddInstanceId(arg interface{}) *Updater {
	u.Add(InstanceId, arg)
	return u
}

func (u *Updater) SetPayload(arg string) *Updater {
	u.Set(Payload, arg)
	return u
}

func (u *Updater) SetCreatedAt(arg time.Time) *Updater {
	u.Set(CreatedAt, arg)
	return u
}
