// Code generated by crud. DO NOT EDIT.

package refreshtokens

import (
	"time"

	"github.com/goflower-io/xsql"
	"github.com/goflower-io/xsql/dialect"
	"maps"
	"slices"
)

type RefreshTokens struct {
	Id         int64     `json:"id"`          //
	InstanceId int64     `json:"instance_id"` //
	Token      string    `json:"token"`       //
	UserId     int64     `json:"user_id"`     //
	Revoked    int64     `json:"revoked"`     //
	CreatedAt  time.Time `json:"created_at"`  //
	UpdatedAt  time.Time `json:"updated_at"`  //
}

const (
	// table tableName is refresh_tokens
	table = "refresh_tokens"
	//Id
	Id = "id"
	//InstanceId
	InstanceId = "instance_id"
	//Token
	Token = "token"
	//UserId
	UserId = "user_id"
	//Revoked
	Revoked = "revoked"
	//CreatedAt
	CreatedAt = "created_at"
	//UpdatedAt
	UpdatedAt = "updated_at"
)

var columns = []string{
	Id,
	InstanceId,
	Token,
	UserId,
	Revoked,
	CreatedAt,
	UpdatedAt,
}

var columnsSet = map[string]struct{}{
	Id:         {},
	InstanceId: {},
	Token:      {},
	UserId:     {},
	Revoked:    {},
	CreatedAt:  {},
	UpdatedAt:  {},
}

func Columns() []string {
	return slices.Clone(columns)
}
func ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}

func (a *RefreshTokens) NewPtr() any {
	return &RefreshTokens{}
}
func (a *RefreshTokens) IsNil() bool {
	return a == nil
}

func (u *RefreshTokens) ScanDst(aa any, columns []string) []any {
	if a, ok := aa.(*RefreshTokens); ok {
		dst := make([]interface{}, 0, len(columns))
		for _, v := range columns {
			switch v {
			case Id:
				dst = append(dst, &a.Id)
			case InstanceId:
				dst = append(dst, &a.InstanceId)
			case Token:
				dst = append(dst, &a.Token)
			case UserId:
				dst = append(dst, &a.UserId)
			case Revoked:
				dst = append(dst, &a.Revoked)
			case CreatedAt:
				dst = append(dst, &a.CreatedAt)
			case UpdatedAt:
				dst = append(dst, &a.UpdatedAt)
			}
		}
		return dst
	}
	return []any{}

}

func (a *RefreshTokens) Values() []any {
	if a.IsNil() {
		return []any{}
	}
	return []interface{}{a.Id, a.InstanceId, a.Token, a.UserId, a.Revoked, a.CreatedAt, a.UpdatedAt}
}
func (a *RefreshTokens) GetAutoIncrPk() (int64, string) {

	if a.IsNil() {
		return 0, Id
	}
	return a.Id, Id

}
func (a *RefreshTokens) SetAutoIncrPk(id int64) {

	if a.IsNil() {
		return
	}
	a.Id = int64(id)

}

func (a *RefreshTokens) Columns() []string {
	return slices.Clone(columns)
}
func (a *RefreshTokens) ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}
func (a *RefreshTokens) Schema() string {
	return ""
}

func (a *RefreshTokens) Dialect() string {

	return dialect.MySQL
}
func (a *RefreshTokens) Table() string {
	return table
}

const (
	IdOp = xsql.FieldOp[int64](Id)

	InstanceIdOp = xsql.FieldOp[int64](InstanceId)

	TokenOp = xsql.StrFieldOp(Token)

	UserIdOp = xsql.FieldOp[int64](UserId)

	RevokedOp = xsql.FieldOp[int64](Revoked)

	CreatedAtOp = xsql.FieldOp[string](CreatedAt)

	UpdatedAtOp = xsql.FieldOp[string](UpdatedAt)
)

func And(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.AndOp(predicates...)
}
func Or(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.OrOp(predicates...)
}
func Not(predicate xsql.WhereFunc) xsql.WhereFunc {
	return xsql.NotOp(predicate)
}

func Create(db xsql.ExecQuerier) *Creater {
	return &Creater{xsql.NewInsertExecutor[*RefreshTokens](db)}
}

type Creater struct {
	*xsql.InsertExecutor[*RefreshTokens]
}

func (c *Creater) SetRefreshTokens(a ...*RefreshTokens) *Creater {
	c.SetItems(a...)
	return c
}

func Find(db xsql.ExecQuerier) *xsql.SelectExecutor[*RefreshTokens] {
	return xsql.NewSelectExecutor[*RefreshTokens](db)
}
func Delete(db xsql.ExecQuerier) *xsql.DeleteExecutor[*RefreshTokens] {
	return xsql.NewDeleteExecutor[*RefreshTokens](db)
}
func Update(db xsql.ExecQuerier) *Updater {
	return &Updater{xsql.NewUpdateExecutor[*RefreshTokens](db)}
}

type Updater struct {
	*xsql.UpdateExecutor[*RefreshTokens]
}

func (u *Updater) SetId(arg int64) *Updater {
	u.Set(Id, arg)
	return u
}

func (u *Updater) SetInstanceId(arg int64) *Updater {
	u.Set(InstanceId, arg)
	return u
}

func (u *Updater) AddInstanceId(arg interface{}) *Updater {
	u.Add(InstanceId, arg)
	return u
}

func (u *Updater) SetToken(arg string) *Updater {
	u.Set(Token, arg)
	return u
}

func (u *Updater) SetUserId(arg int64) *Updater {
	u.Set(UserId, arg)
	return u
}

func (u *Updater) AddUserId(arg interface{}) *Updater {
	u.Add(UserId, arg)
	return u
}

func (u *Updater) SetRevoked(arg int64) *Updater {
	u.Set(Revoked, arg)
	return u
}

func (u *Updater) AddRevoked(arg interface{}) *Updater {
	u.Add(Revoked, arg)
	return u
}

func (u *Updater) SetCreatedAt(arg time.Time) *Updater {
	u.Set(CreatedAt, arg)
	return u
}

func (u *Updater) SetUpdatedAt(arg time.Time) *Updater {
	u.Set(UpdatedAt, arg)
	return u
}
