// Code generated by crud. DO NOT EDIT.

package instances

import (
	"time"

	"github.com/goflower-io/xsql"
	"github.com/goflower-io/xsql/dialect"
	"maps"
	"slices"
)

type Instances struct {
	Id            int64     `json:"id"`              //
	Uuid          string    `json:"uuid"`            //
	RawBaseConfig string    `json:"raw_base_config"` //
	CreatedAt     time.Time `json:"created_at"`      //
	UpdatedAt     time.Time `json:"updated_at"`      //
}

const (
	// table tableName is instances
	table = "instances"
	//Id
	Id = "id"
	//Uuid
	Uuid = "uuid"
	//RawBaseConfig
	RawBaseConfig = "raw_base_config"
	//CreatedAt
	CreatedAt = "created_at"
	//UpdatedAt
	UpdatedAt = "updated_at"
)

var columns = []string{
	Id,
	Uuid,
	RawBaseConfig,
	CreatedAt,
	UpdatedAt,
}

var columnsSet = map[string]struct{}{
	Id:            {},
	Uuid:          {},
	RawBaseConfig: {},
	CreatedAt:     {},
	UpdatedAt:     {},
}

func Columns() []string {
	return slices.Clone(columns)
}
func ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}

func (a *Instances) NewPtr() any {
	return &Instances{}
}
func (a *Instances) IsNil() bool {
	return a == nil
}

func (u *Instances) ScanDst(aa any, columns []string) []any {
	if a, ok := aa.(*Instances); ok {
		dst := make([]interface{}, 0, len(columns))
		for _, v := range columns {
			switch v {
			case Id:
				dst = append(dst, &a.Id)
			case Uuid:
				dst = append(dst, &a.Uuid)
			case RawBaseConfig:
				dst = append(dst, &a.RawBaseConfig)
			case CreatedAt:
				dst = append(dst, &a.CreatedAt)
			case UpdatedAt:
				dst = append(dst, &a.UpdatedAt)
			}
		}
		return dst
	}
	return []any{}

}

func (a *Instances) Values() []any {
	if a.IsNil() {
		return []any{}
	}
	return []interface{}{a.Id, a.Uuid, a.RawBaseConfig, a.CreatedAt, a.UpdatedAt}
}
func (a *Instances) GetAutoIncrPk() (int64, string) {

	if a.IsNil() {
		return 0, Id
	}
	return a.Id, Id

}
func (a *Instances) SetAutoIncrPk(id int64) {

	if a.IsNil() {
		return
	}
	a.Id = int64(id)

}

func (a *Instances) Columns() []string {
	return slices.Clone(columns)
}
func (a *Instances) ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}
func (a *Instances) Schema() string {
	return ""
}

func (a *Instances) Dialect() string {

	return dialect.MySQL
}
func (a *Instances) Table() string {
	return table
}

const (
	IdOp = xsql.FieldOp[int64](Id)

	UuidOp = xsql.StrFieldOp(Uuid)

	CreatedAtOp = xsql.FieldOp[string](CreatedAt)

	UpdatedAtOp = xsql.FieldOp[string](UpdatedAt)
)

func And(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.AndOp(predicates...)
}
func Or(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.OrOp(predicates...)
}
func Not(predicate xsql.WhereFunc) xsql.WhereFunc {
	return xsql.NotOp(predicate)
}

func Create(db xsql.ExecQuerier) *Creater {
	return &Creater{xsql.NewInsertExecutor[*Instances](db)}
}

type Creater struct {
	*xsql.InsertExecutor[*Instances]
}

func (c *Creater) SetInstances(a ...*Instances) *Creater {
	c.SetItems(a...)
	return c
}

func Find(db xsql.ExecQuerier) *xsql.SelectExecutor[*Instances] {
	return xsql.NewSelectExecutor[*Instances](db)
}
func Delete(db xsql.ExecQuerier) *xsql.DeleteExecutor[*Instances] {
	return xsql.NewDeleteExecutor[*Instances](db)
}
func Update(db xsql.ExecQuerier) *Updater {
	return &Updater{xsql.NewUpdateExecutor[*Instances](db)}
}

type Updater struct {
	*xsql.UpdateExecutor[*Instances]
}

func (u *Updater) SetId(arg int64) *Updater {
	u.Set(Id, arg)
	return u
}

func (u *Updater) SetUuid(arg string) *Updater {
	u.Set(Uuid, arg)
	return u
}

func (u *Updater) SetRawBaseConfig(arg string) *Updater {
	u.Set(RawBaseConfig, arg)
	return u
}

func (u *Updater) SetCreatedAt(arg time.Time) *Updater {
	u.Set(CreatedAt, arg)
	return u
}

func (u *Updater) SetUpdatedAt(arg time.Time) *Updater {
	u.Set(UpdatedAt, arg)
	return u
}
