// Code generated by crud. DO NOT EDIT.

package users

import (
	"time"

	"github.com/goflower-io/xsql"
	"github.com/goflower-io/xsql/dialect"
	"maps"
	"slices"
)

type Users struct {
	Id                 int64     `json:"id"`                   //
	InstanceId         int64     `json:"instance_id"`          //
	Aud                string    `json:"aud"`                  //
	Role               string    `json:"role"`                 //
	Email              string    `json:"email"`                //
	EncryptedPassword  string    `json:"encrypted_password"`   //
	ConfirmedAt        time.Time `json:"confirmed_at"`         //
	InvitedAt          time.Time `json:"invited_at"`           //
	ConfirmationToken  string    `json:"confirmation_token"`   //
	ConfirmationSentAt time.Time `json:"confirmation_sent_at"` //
	RecoveryToken      string    `json:"recovery_token"`       //
	RecoverySentAt     time.Time `json:"recovery_sent_at"`     //
	EmailChangeToken   string    `json:"email_change_token"`   //
	EmailChange        string    `json:"email_change"`         //
	EmailChangeSentAt  time.Time `json:"email_change_sent_at"` //
	LastSignInAt       time.Time `json:"last_sign_in_at"`      //
	RawAppMetaData     string    `json:"raw_app_meta_data"`    //
	RawUserMetaData    string    `json:"raw_user_meta_data"`   //
	IsSuperAdmin       int64     `json:"is_super_admin"`       //
	CreatedAt          time.Time `json:"created_at"`           //
	UpdatedAt          time.Time `json:"updated_at"`           //
}

const (
	// table tableName is users
	table = "users"
	//Id
	Id = "id"
	//InstanceId
	InstanceId = "instance_id"
	//Aud
	Aud = "aud"
	//Role
	Role = "role"
	//Email
	Email = "email"
	//EncryptedPassword
	EncryptedPassword = "encrypted_password"
	//ConfirmedAt
	ConfirmedAt = "confirmed_at"
	//InvitedAt
	InvitedAt = "invited_at"
	//ConfirmationToken
	ConfirmationToken = "confirmation_token"
	//ConfirmationSentAt
	ConfirmationSentAt = "confirmation_sent_at"
	//RecoveryToken
	RecoveryToken = "recovery_token"
	//RecoverySentAt
	RecoverySentAt = "recovery_sent_at"
	//EmailChangeToken
	EmailChangeToken = "email_change_token"
	//EmailChange
	EmailChange = "email_change"
	//EmailChangeSentAt
	EmailChangeSentAt = "email_change_sent_at"
	//LastSignInAt
	LastSignInAt = "last_sign_in_at"
	//RawAppMetaData
	RawAppMetaData = "raw_app_meta_data"
	//RawUserMetaData
	RawUserMetaData = "raw_user_meta_data"
	//IsSuperAdmin
	IsSuperAdmin = "is_super_admin"
	//CreatedAt
	CreatedAt = "created_at"
	//UpdatedAt
	UpdatedAt = "updated_at"
)

var columns = []string{
	Id,
	InstanceId,
	Aud,
	Role,
	Email,
	EncryptedPassword,
	ConfirmedAt,
	InvitedAt,
	ConfirmationToken,
	ConfirmationSentAt,
	RecoveryToken,
	RecoverySentAt,
	EmailChangeToken,
	EmailChange,
	EmailChangeSentAt,
	LastSignInAt,
	RawAppMetaData,
	RawUserMetaData,
	IsSuperAdmin,
	CreatedAt,
	UpdatedAt,
}

var columnsSet = map[string]struct{}{
	Id:                 {},
	InstanceId:         {},
	Aud:                {},
	Role:               {},
	Email:              {},
	EncryptedPassword:  {},
	ConfirmedAt:        {},
	InvitedAt:          {},
	ConfirmationToken:  {},
	ConfirmationSentAt: {},
	RecoveryToken:      {},
	RecoverySentAt:     {},
	EmailChangeToken:   {},
	EmailChange:        {},
	EmailChangeSentAt:  {},
	LastSignInAt:       {},
	RawAppMetaData:     {},
	RawUserMetaData:    {},
	IsSuperAdmin:       {},
	CreatedAt:          {},
	UpdatedAt:          {},
}

func Columns() []string {
	return slices.Clone(columns)
}
func ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}

func (a *Users) NewPtr() any {
	return &Users{}
}
func (a *Users) IsNil() bool {
	return a == nil
}

func (u *Users) ScanDst(aa any, columns []string) []any {
	if a, ok := aa.(*Users); ok {
		dst := make([]interface{}, 0, len(columns))
		for _, v := range columns {
			switch v {
			case Id:
				dst = append(dst, &a.Id)
			case InstanceId:
				dst = append(dst, &a.InstanceId)
			case Aud:
				dst = append(dst, &a.Aud)
			case Role:
				dst = append(dst, &a.Role)
			case Email:
				dst = append(dst, &a.Email)
			case EncryptedPassword:
				dst = append(dst, &a.EncryptedPassword)
			case ConfirmedAt:
				dst = append(dst, &a.ConfirmedAt)
			case InvitedAt:
				dst = append(dst, &a.InvitedAt)
			case ConfirmationToken:
				dst = append(dst, &a.ConfirmationToken)
			case ConfirmationSentAt:
				dst = append(dst, &a.ConfirmationSentAt)
			case RecoveryToken:
				dst = append(dst, &a.RecoveryToken)
			case RecoverySentAt:
				dst = append(dst, &a.RecoverySentAt)
			case EmailChangeToken:
				dst = append(dst, &a.EmailChangeToken)
			case EmailChange:
				dst = append(dst, &a.EmailChange)
			case EmailChangeSentAt:
				dst = append(dst, &a.EmailChangeSentAt)
			case LastSignInAt:
				dst = append(dst, &a.LastSignInAt)
			case RawAppMetaData:
				dst = append(dst, &a.RawAppMetaData)
			case RawUserMetaData:
				dst = append(dst, &a.RawUserMetaData)
			case IsSuperAdmin:
				dst = append(dst, &a.IsSuperAdmin)
			case CreatedAt:
				dst = append(dst, &a.CreatedAt)
			case UpdatedAt:
				dst = append(dst, &a.UpdatedAt)
			}
		}
		return dst
	}
	return []any{}

}

func (a *Users) Values() []any {
	if a.IsNil() {
		return []any{}
	}
	return []interface{}{a.Id, a.InstanceId, a.Aud, a.Role, a.Email, a.EncryptedPassword, a.ConfirmedAt, a.InvitedAt, a.ConfirmationToken, a.ConfirmationSentAt, a.RecoveryToken, a.RecoverySentAt, a.EmailChangeToken, a.EmailChange, a.EmailChangeSentAt, a.LastSignInAt, a.RawAppMetaData, a.RawUserMetaData, a.IsSuperAdmin, a.CreatedAt, a.UpdatedAt}
}
func (a *Users) GetAutoIncrPk() (int64, string) {

	return 0, ""

}
func (a *Users) SetAutoIncrPk(id int64) {

}

func (a *Users) Columns() []string {
	return slices.Clone(columns)
}
func (a *Users) ColumnsSet() map[string]struct{} {
	return maps.Clone(columnsSet)
}
func (a *Users) Schema() string {
	return ""
}

func (a *Users) Dialect() string {

	return dialect.MySQL
}
func (a *Users) Table() string {
	return table
}

const (
	IdOp = xsql.FieldOp[int64](Id)

	InstanceIdOp = xsql.FieldOp[int64](InstanceId)

	AudOp = xsql.StrFieldOp(Aud)

	RoleOp = xsql.StrFieldOp(Role)

	EmailOp = xsql.StrFieldOp(Email)

	EncryptedPasswordOp = xsql.StrFieldOp(EncryptedPassword)

	ConfirmedAtOp = xsql.FieldOp[string](ConfirmedAt)

	InvitedAtOp = xsql.FieldOp[string](InvitedAt)

	ConfirmationTokenOp = xsql.StrFieldOp(ConfirmationToken)

	ConfirmationSentAtOp = xsql.FieldOp[string](ConfirmationSentAt)

	RecoveryTokenOp = xsql.StrFieldOp(RecoveryToken)

	RecoverySentAtOp = xsql.FieldOp[string](RecoverySentAt)

	EmailChangeTokenOp = xsql.StrFieldOp(EmailChangeToken)

	EmailChangeOp = xsql.StrFieldOp(EmailChange)

	EmailChangeSentAtOp = xsql.FieldOp[string](EmailChangeSentAt)

	LastSignInAtOp = xsql.FieldOp[string](LastSignInAt)

	RawAppMetaDataOp = xsql.StrFieldOp(RawAppMetaData)

	RawUserMetaDataOp = xsql.StrFieldOp(RawUserMetaData)

	IsSuperAdminOp = xsql.FieldOp[int64](IsSuperAdmin)

	CreatedAtOp = xsql.FieldOp[string](CreatedAt)

	UpdatedAtOp = xsql.FieldOp[string](UpdatedAt)
)

func And(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.AndOp(predicates...)
}
func Or(predicates ...xsql.WhereFunc) xsql.WhereFunc {
	return xsql.OrOp(predicates...)
}
func Not(predicate xsql.WhereFunc) xsql.WhereFunc {
	return xsql.NotOp(predicate)
}

func Create(db xsql.ExecQuerier) *Creater {
	return &Creater{xsql.NewInsertExecutor[*Users](db)}
}

type Creater struct {
	*xsql.InsertExecutor[*Users]
}

func (c *Creater) SetUsers(a ...*Users) *Creater {
	c.SetItems(a...)
	return c
}

func Find(db xsql.ExecQuerier) *xsql.SelectExecutor[*Users] {
	return xsql.NewSelectExecutor[*Users](db)
}
func Delete(db xsql.ExecQuerier) *xsql.DeleteExecutor[*Users] {
	return xsql.NewDeleteExecutor[*Users](db)
}
func Update(db xsql.ExecQuerier) *Updater {
	return &Updater{xsql.NewUpdateExecutor[*Users](db)}
}

type Updater struct {
	*xsql.UpdateExecutor[*Users]
}

func (u *Updater) SetId(arg int64) *Updater {
	u.Set(Id, arg)
	return u
}

func (u *Updater) SetInstanceId(arg int64) *Updater {
	u.Set(InstanceId, arg)
	return u
}

func (u *Updater) AddInstanceId(arg interface{}) *Updater {
	u.Add(InstanceId, arg)
	return u
}

func (u *Updater) SetAud(arg string) *Updater {
	u.Set(Aud, arg)
	return u
}

func (u *Updater) SetRole(arg string) *Updater {
	u.Set(Role, arg)
	return u
}

func (u *Updater) SetEmail(arg string) *Updater {
	u.Set(Email, arg)
	return u
}

func (u *Updater) SetEncryptedPassword(arg string) *Updater {
	u.Set(EncryptedPassword, arg)
	return u
}

func (u *Updater) SetConfirmedAt(arg time.Time) *Updater {
	u.Set(ConfirmedAt, arg)
	return u
}

func (u *Updater) SetInvitedAt(arg time.Time) *Updater {
	u.Set(InvitedAt, arg)
	return u
}

func (u *Updater) SetConfirmationToken(arg string) *Updater {
	u.Set(ConfirmationToken, arg)
	return u
}

func (u *Updater) SetConfirmationSentAt(arg time.Time) *Updater {
	u.Set(ConfirmationSentAt, arg)
	return u
}

func (u *Updater) SetRecoveryToken(arg string) *Updater {
	u.Set(RecoveryToken, arg)
	return u
}

func (u *Updater) SetRecoverySentAt(arg time.Time) *Updater {
	u.Set(RecoverySentAt, arg)
	return u
}

func (u *Updater) SetEmailChangeToken(arg string) *Updater {
	u.Set(EmailChangeToken, arg)
	return u
}

func (u *Updater) SetEmailChange(arg string) *Updater {
	u.Set(EmailChange, arg)
	return u
}

func (u *Updater) SetEmailChangeSentAt(arg time.Time) *Updater {
	u.Set(EmailChangeSentAt, arg)
	return u
}

func (u *Updater) SetLastSignInAt(arg time.Time) *Updater {
	u.Set(LastSignInAt, arg)
	return u
}

func (u *Updater) SetRawAppMetaData(arg string) *Updater {
	u.Set(RawAppMetaData, arg)
	return u
}

func (u *Updater) SetRawUserMetaData(arg string) *Updater {
	u.Set(RawUserMetaData, arg)
	return u
}

func (u *Updater) SetIsSuperAdmin(arg int64) *Updater {
	u.Set(IsSuperAdmin, arg)
	return u
}

func (u *Updater) AddIsSuperAdmin(arg interface{}) *Updater {
	u.Add(IsSuperAdmin, arg)
	return u
}

func (u *Updater) SetCreatedAt(arg time.Time) *Updater {
	u.Set(CreatedAt, arg)
	return u
}

func (u *Updater) SetUpdatedAt(arg time.Time) *Updater {
	u.Set(UpdatedAt, arg)
	return u
}
